### ISSUE TITLE
diffset@v1 not found

### ISSUE THREAD

**Issue by P4sca1** [softprops/diffset#4] opened 2020-04-16 20:39 UTC
Hey there!
First of all thanks for making this action, it is really useful to improve linting time! :)

I noticed that the README shows to use `softprops/diffset@v1`, but latest version is `softprops/diffset@v0.1.1`

**Comment by P4sca1** [comment] 2020-04-16 20:56
Okay for some reason I also get the error when using `softprops/diffset@v0.1.1`.

Logs:
```
2020-04-16T20:50:29.2268150Z ##[group]Run softprops/diffset@v0.1.1
2020-04-16T20:50:29.2268951Z with:
2020-04-16T20:50:29.2270049Z   lint_files: apps/***api,daemon***/src/**/*.***js,ts***
apps/frontend/**/*.***js,ts,vue***
packages/***convert-yup-error,pino-sentry-stream***/src/**/*.***js,ts***

2020-04-16T20:50:29.2270388Z env:
2020-04-16T20:50:29.2270655Z   NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
2020-04-16T20:50:29.2270940Z   NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
2020-04-16T20:50:29.2271410Z   GITHUB_TOKEN: ***
2020-04-16T20:50:29.2271663Z ##[endgroup]
2020-04-16T20:50:29.5664731Z ##[error]Not Found
```

**Comment by softprops** [comment] 2020-04-16 21:08
hrm. I can confirm both of these tags are available 

https://github.com/softprops/diffset/tree/v1 
https://github.com/softprops/diffset/tree/v0.1.1

**Comment by P4sca1** [comment] 2020-04-16 21:23
After further digging into the logs I can confirm that the tags are not a problem. The action downloads just fine. But when it runs, it exits immediately with the `Not found` error.
Is it intended that this action interrupts the job when no pattern is matched?

**Comment by awisniew90** [comment] 2021-01-26 01:53
I'm also hitting this issue when I try to use:

```
with:
  base: main
```

**Comment by LuizCristino** [comment] 2021-02-07 14:34
Having the same problem as @awisniew90

**Comment by softprops** [comment] 2021-03-15 04:10
I just updated the v1 tag with a few fixes one which might address the issue here. 

I've only been using this with `push` triggers. I found that with `pull_request` triggers it didn't work because of a quirk the value uses for the  `GITHUB_REF` env variable for pull request events.

This should now work with both `push` and `pull_request` triggers.

**Comment by chenrui333** [comment] 2024-06-19 15:35
gonna close the issue for now (as I just released v2)

**Closed by chenrui333** 2024-06-19 15:35 UTC
